language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip에 포함할 파일을 담을 디렉토리
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # 담은 파일들 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리에 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/lec1.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # 엑세스 키
    secret_access_key: $AWS_SECRET_KEY # 비밀 엑세스 키
    bucket: chae-springboot-build # 버킷 이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 접근 private
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # 엑세스 키
    secret_access_key: $AWS_SECRET_KEY # 비밀 엑세스 키
    bucket: chae-springboot-build # 버킷 이름
    key: lec1.zip
    bundle_type: zip
    application: freelec-springboot2-webservice
    deployment_group: freelec-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - chsj9251@naver.com